import "./globals.css";
import { matter } from "@/fonts/index.ts";
import { Navbar } from "@/components";
export const metadata = {
  title: "Travlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={matter.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
